-- ─── Meaningfulness & Stressfulness: new activity-level ratings ───────────────
-- Two new 5-point ratings asked on the same screen as the existing Satisfaction
-- rating, at the end of each activity entry. Admin-toggleable per course via
-- course.ask_extra_ratings (default off — existing courses are unaffected).
--
-- Both lookup tables mirror `satisfaction`'s shape exactly (id, code, name,
-- name_en), but use an ascending low→high code convention (1=lowest,
-- 5=highest) rather than satisfaction's best→worst convention, since these
-- are intensity scales, not valence scales.

-- ─── meaningfulness ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.meaningfulness (
  meaningfulness_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              text    NOT NULL UNIQUE,
  name              text    NOT NULL,
  name_en           text    NOT NULL
);

INSERT INTO public.meaningfulness (code, name, name_en) VALUES
  ('1', 'Sehr niedrig', 'Very low'),
  ('2', 'Niedrig', 'Low'),
  ('3', 'Mittel', 'Medium'),
  ('4', 'Hoch', 'High'),
  ('5', 'Sehr hoch', 'Very high')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.meaningfulness ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read meaningfulness" ON public.meaningfulness;
CREATE POLICY "Authenticated users can read meaningfulness"
  ON public.meaningfulness FOR SELECT
  TO authenticated
  USING (true);

-- ─── stressfulness ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.stressfulness (
  stressfulness_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             text    NOT NULL UNIQUE,
  name             text    NOT NULL,
  name_en          text    NOT NULL
);

INSERT INTO public.stressfulness (code, name, name_en) VALUES
  ('1', 'Sehr niedrig', 'Very low'),
  ('2', 'Niedrig', 'Low'),
  ('3', 'Mittel', 'Medium'),
  ('4', 'Hoch', 'High'),
  ('5', 'Sehr hoch', 'Very high')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.stressfulness ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read stressfulness" ON public.stressfulness;
CREATE POLICY "Authenticated users can read stressfulness"
  ON public.stressfulness FOR SELECT
  TO authenticated
  USING (true);

-- ─── time_entry: nullable FKs, same pattern as satisfaction_id ─────────────

ALTER TABLE public.time_entry
  ADD COLUMN IF NOT EXISTS meaningfulness_id integer REFERENCES public.meaningfulness(meaningfulness_id),
  ADD COLUMN IF NOT EXISTS stressfulness_id  integer REFERENCES public.stressfulness(stressfulness_id);

-- ─── course: per-course opt-in toggle ───────────────────────────────────────
-- Combined toggle for both Meaningfulness and Stressfulness together.
-- Mirrors the existing comparison_enabled toggle: boolean, default false,
-- freely editable any time from the admin course-detail view.

ALTER TABLE public.course
  ADD COLUMN IF NOT EXISTS ask_extra_ratings boolean NOT NULL DEFAULT false;
