CREATE TABLE IF NOT EXISTS public.security_question (
  security_question_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.user_security_question (
  user_security_question_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profiles_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  security_question_id integer NOT NULL REFERENCES public.security_question(security_question_id),
  answer_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT user_security_question_unique_per_question UNIQUE (profiles_id, security_question_id)
);

CREATE TABLE IF NOT EXISTS public.security_question_reset_challenge (
  security_question_reset_challenge_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profiles_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.admin_password_reset_log (
  admin_password_reset_log_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  triggered_by_profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_user_security_question_updated_at ON public.user_security_question;
CREATE TRIGGER trg_user_security_question_updated_at
  BEFORE UPDATE ON public.user_security_question
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.security_question ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_security_question ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_question_reset_challenge ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_password_reset_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read security questions" ON public.security_question;
CREATE POLICY "Authenticated users can read security questions"
  ON public.security_question FOR SELECT
  TO authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS "Admins can manage security questions" ON public.security_question;
CREATE POLICY "Admins can manage security questions"
  ON public.security_question FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Users can read own security question answers" ON public.user_security_question;
CREATE POLICY "Users can read own security question answers"
  ON public.user_security_question FOR SELECT
  TO authenticated
  USING (profiles_id = auth.uid());

DROP POLICY IF EXISTS "Users can insert own security question answers" ON public.user_security_question;
CREATE POLICY "Users can insert own security question answers"
  ON public.user_security_question FOR INSERT
  TO authenticated
  WITH CHECK (profiles_id = auth.uid());

DROP POLICY IF EXISTS "Users can update own security question answers" ON public.user_security_question;
CREATE POLICY "Users can update own security question answers"
  ON public.user_security_question FOR UPDATE
  TO authenticated
  USING (profiles_id = auth.uid())
  WITH CHECK (profiles_id = auth.uid());

DROP POLICY IF EXISTS "Users can delete own security question answers" ON public.user_security_question;
CREATE POLICY "Users can delete own security question answers"
  ON public.user_security_question FOR DELETE
  TO authenticated
  USING (profiles_id = auth.uid());

DROP POLICY IF EXISTS "Admins can read all user security questions" ON public.user_security_question;
CREATE POLICY "Admins can read all user security questions"
  ON public.user_security_question FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can update all user security questions" ON public.user_security_question;
CREATE POLICY "Admins can update all user security questions"
  ON public.user_security_question FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Service role manages reset challenges" ON public.security_question_reset_challenge;
CREATE POLICY "Service role manages reset challenges"
  ON public.security_question_reset_challenge FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can insert password reset logs" ON public.admin_password_reset_log;
CREATE POLICY "Admins can insert password reset logs"
  ON public.admin_password_reset_log FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can read password reset logs" ON public.admin_password_reset_log;
CREATE POLICY "Admins can read password reset logs"
  ON public.admin_password_reset_log FOR SELECT
  TO authenticated
  USING (public.is_admin());

INSERT INTO public.security_question (question_text, sort_order)
VALUES
  ('In welcher Stadt bist du geboren?', 1),
  ('Wie hiess dein erstes Haustier?', 2),
  ('Was ist deine Lieblingsfarbe?', 3),
  ('Was ist dein Lieblingsverein?', 4),
  ('Wie hiess deine erste Schule?', 5),
  ('Was ist dein Lieblingsessen?', 6),
  ('Wie hiess dein bester Freund in der Kindheit?', 7),
  ('Was ist dein Lieblingsfach?', 8)
ON CONFLICT (question_text) DO NOTHING;