-- ─── Day questionnaire: mandatory end-of-day questions ─────────────────────
-- The moment a day reaches 144/144 filled slots, the app shows a mandatory
-- popup asking 8 questions about the day as a whole (based on the HETUS-style
-- reference diary form, with agreed modifications: Q1 gets a simplified 4th
-- option, Q2-4 pick from that day's own primary activities, Q7a "are you a
-- student or employed" and Q8b "how far did you travel" are dropped, Q7b
-- becomes unconditional). Admin-toggleable per course via
-- course.ask_day_questionnaire (default off — existing courses unaffected).
--
-- All lookup tables mirror the existing convention: {id}, code, name (German),
-- name_en (English).

-- ─── diary_fill_timing (Q1: "When did you fill in the diary?") ─────────────

CREATE TABLE IF NOT EXISTS public.diary_fill_timing (
  diary_fill_timing_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                  text    NOT NULL UNIQUE,
  name                  text    NOT NULL,
  name_en               text    NOT NULL
);

INSERT INTO public.diary_fill_timing (code, name, name_en) VALUES
  ('1', 'Zwischendurch während des Tagebuchtages', 'Now and then during the diary day'),
  ('2', 'Am Ende des Tagebuchtages', 'At the end of the diary day'),
  ('3', 'Am Tag nach dem Tagebuchtag', 'The day after the diary day'),
  ('4', 'Zwei oder mehr Tage nach dem Tagebuchtag', 'Two or more days after the diary day')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.diary_fill_timing ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read diary_fill_timing" ON public.diary_fill_timing;
CREATE POLICY "Authenticated users can read diary_fill_timing"
  ON public.diary_fill_timing FOR SELECT
  TO authenticated
  USING (true);

-- ─── day_type_context (Q7b: "What kind of day was this?", now unconditional) ─

CREATE TABLE IF NOT EXISTS public.day_type_context (
  day_type_context_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                 text    NOT NULL UNIQUE,
  name                 text    NOT NULL,
  name_en              text    NOT NULL
);

INSERT INTO public.day_type_context (code, name, name_en) VALUES
  ('1', 'Gewöhnlicher Arbeitstag', 'Ordinary work day'),
  ('2', 'Gewöhnlicher Schultag', 'Ordinary school day'),
  ('3', 'Freier Tag (Wochenende/Feiertag/Arbeitsplan)', 'Day off (weekend/holiday/schedule)'),
  ('4', 'Krankheitstag', 'Sick day'),
  ('5', 'Ferientag', 'Vacation day'),
  ('6', 'Frei aus anderen Gründen', 'Off for other reasons')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.day_type_context ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read day_type_context" ON public.day_type_context;
CREATE POLICY "Authenticated users can read day_type_context"
  ON public.day_type_context FOR SELECT
  TO authenticated
  USING (true);

-- ─── trip_type (Q8a: "Were you on a trip during the diary day?") ───────────

CREATE TABLE IF NOT EXISTS public.trip_type (
  trip_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         text    NOT NULL UNIQUE,
  name         text    NOT NULL,
  name_en      text    NOT NULL
);

INSERT INTO public.trip_type (code, name, name_en) VALUES
  ('1', 'Nein', 'No'),
  ('2', 'Ja, Tagesausflug im Inland', 'Yes, a single-day trip within the country'),
  ('3', 'Ja, Tagesausflug im Ausland', 'Yes, a single-day trip abroad'),
  ('4', 'Ja, Übernachtung im Inland', 'Yes, an overnight trip within the country'),
  ('5', 'Ja, Übernachtung im Ausland', 'Yes, an overnight trip abroad')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.trip_type ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read trip_type" ON public.trip_type;
CREATE POLICY "Authenticated users can read trip_type"
  ON public.trip_type FOR SELECT
  TO authenticated
  USING (true);

-- ─── day_appreciation (Q5: "Overall, how do you appreciate this day?") ─────
-- Code 1=best..5=worst, matching satisfaction's valence-scale convention
-- (unlike meaningfulness/stressfulness, which are intensity scales).

CREATE TABLE IF NOT EXISTS public.day_appreciation (
  day_appreciation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                 text    NOT NULL UNIQUE,
  name                 text    NOT NULL,
  name_en              text    NOT NULL
);

INSERT INTO public.day_appreciation (code, name, name_en) VALUES
  ('1', 'Sehr angenehm', 'Very pleasant'),
  ('2', 'Angenehm', 'Pleasant'),
  ('3', 'Weder angenehm noch unangenehm', 'Neither pleasant nor unpleasant'),
  ('4', 'Unangenehm', 'Unpleasant'),
  ('5', 'Sehr unangenehm', 'Very unpleasant')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.day_appreciation ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read day_appreciation" ON public.day_appreciation;
CREATE POLICY "Authenticated users can read day_appreciation"
  ON public.day_appreciation FOR SELECT
  TO authenticated
  USING (true);

-- ─── course: per-course opt-in toggle ───────────────────────────────────────

ALTER TABLE public.course
  ADD COLUMN IF NOT EXISTS ask_day_questionnaire boolean NOT NULL DEFAULT false;

-- ─── day_questionnaire: one row per completed day ──────────────────────────
-- All FK columns are NOT NULL: the questionnaire is all-or-nothing once shown
-- (no more conditional branching, since Q7a/Q8b were dropped). Q2-4 reference
-- `activity` directly (the student's most pleasant/unpleasant/stressful
-- *activity* that day, picked from their own primary activities — not a
-- specific time_entry occurrence).

CREATE TABLE IF NOT EXISTS public.day_questionnaire (
  day_questionnaire_id      integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_id                    integer     NOT NULL UNIQUE REFERENCES public.day(day_id) ON DELETE CASCADE,
  diary_fill_timing_id      integer     NOT NULL REFERENCES public.diary_fill_timing(diary_fill_timing_id),
  most_pleasant_activity_id integer     NOT NULL REFERENCES public.activity(activity_id),
  most_unpleasant_activity_id integer   NOT NULL REFERENCES public.activity(activity_id),
  most_stressful_activity_id integer    NOT NULL REFERENCES public.activity(activity_id),
  day_appreciation_id       integer     NOT NULL REFERENCES public.day_appreciation(day_appreciation_id),
  is_unusual_day             boolean    NOT NULL,
  day_type_context_id       integer     NOT NULL REFERENCES public.day_type_context(day_type_context_id),
  trip_type_id               integer    NOT NULL REFERENCES public.trip_type(trip_type_id),
  created_at                 timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at                 timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- Reuses public.set_updated_at(), already defined in
-- 20260502000000_add_security_questions.sql.
DROP TRIGGER IF EXISTS trg_day_questionnaire_updated_at ON public.day_questionnaire;
CREATE TRIGGER trg_day_questionnaire_updated_at
  BEFORE UPDATE ON public.day_questionnaire
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.day_questionnaire ENABLE ROW LEVEL SECURITY;

-- Users can read/insert/update their own day_questionnaire rows (via the
-- same day.profiles_id = auth.uid() join used for time_entry). Update is
-- permitted (rather than insert-only) so a client-side retry after a
-- network failure can safely upsert on day_id without erroring.
DROP POLICY IF EXISTS "Users can read own day_questionnaire" ON public.day_questionnaire;
CREATE POLICY "Users can read own day_questionnaire"
  ON public.day_questionnaire FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.day
      WHERE day.day_id = day_questionnaire.day_id
        AND day.profiles_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can insert own day_questionnaire" ON public.day_questionnaire;
CREATE POLICY "Users can insert own day_questionnaire"
  ON public.day_questionnaire FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.day
      WHERE day.day_id = day_questionnaire.day_id
        AND day.profiles_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can update own day_questionnaire" ON public.day_questionnaire;
CREATE POLICY "Users can update own day_questionnaire"
  ON public.day_questionnaire FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.day
      WHERE day.day_id = day_questionnaire.day_id
        AND day.profiles_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.day
      WHERE day.day_id = day_questionnaire.day_id
        AND day.profiles_id = auth.uid()
    )
  );

-- Admins can read all day_questionnaire rows in principle (permissive) —
-- but see the RESTRICTIVE policy below, which mirrors the ethics-review
-- constraint already applied to time_entry in
-- 20260916000000_admin_no_time_entry_access.sql: admins are blocked from
-- reading OTHER users' day_questionnaire answers. Aggregated, de-identified
-- admin statistics must go through app/api/admin/* using the service-role
-- client, exactly like time_entry already does (see lib/admin/statistics.ts).
DROP POLICY IF EXISTS "Admins can read all day_questionnaire" ON public.day_questionnaire;
CREATE POLICY "Admins can read all day_questionnaire"
  ON public.day_questionnaire FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admins cannot read others day_questionnaire" ON public.day_questionnaire;
CREATE POLICY "Admins cannot read others day_questionnaire"
  ON public.day_questionnaire
  AS RESTRICTIVE
  FOR SELECT
  TO authenticated
  USING (
    NOT public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.day
      WHERE day.day_id = day_questionnaire.day_id
        AND day.profiles_id = auth.uid()
    )
  );
